title: Teaching You How To Learn
description: 
show_downloads: false
google_analytics:
# theme: jekyll-theme-cayman
paginate: 4
baseurl: /alex-cayman-theme

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
